//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkspace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblWorkspace()
        {
            this.tblWorkspaceMembers = new HashSet<tblWorkspaceMember>();
        }
    
        public int WorkspaceId { get; set; }
        public Nullable<int> WorkspaceAdminId { get; set; }
        public Nullable<int> ProjectId { get; set; }
    
        public virtual tblProject tblProject { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkspaceMember> tblWorkspaceMembers { get; set; }
    }
}
