//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblProjects = new HashSet<tblProject>();
            this.tblProjectMembers = new HashSet<tblProjectMember>();
            this.tblWorkspaces = new HashSet<tblWorkspace>();
            this.tblWorkspaceMembers = new HashSet<tblWorkspaceMember>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> UserDOB { get; set; }
        public string UserGender { get; set; }
        public string UserProfileImage { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public string UserBio { get; set; }
        public string UserOrganisation { get; set; }
        public string UserUserName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProject> tblProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProjectMember> tblProjectMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkspace> tblWorkspaces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkspaceMember> tblWorkspaceMembers { get; set; }
        public string GUID { get; set; }
        public bool UserStatus { get;  set; }
    }
}
