//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkspaceMember
    {
        public Nullable<int> UserId { get; set; }
        public Nullable<int> WorkspaceId { get; set; }
        public int WorkspaceMember { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblWorkspace tblWorkspace { get; set; }
    }
}
